### ISSUE TITLE
[Bug]: Missing json2html package in requirements

### ISSUE THREAD

**Issue by Kacperxxx** [mlops-ai/mlops#118]
### Contact Details

kac.pekalski1@gmail.com

### What happened?

The json2html package is missing from the requirements and must be manually installed

### Version

1.2.7

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by directtt** [comment]
Hello @Kacperxxx , sorry to hear that, our team is working to fix that ASAP!

**Comment by directtt** [comment]
Fixed in version 1.2.8 😎 👍

**Comment by Kacperxxx** [comment]
Thanks!
